# Generated by Django 4.0.3 on 2022-03-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренд'},
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ratingstar', verbose_name='Звезда'),
        ),
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.ManyToManyField(blank=True, to='shop.operatingsystems', verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.ManyToManyField(blank=True, to='shop.platform', verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.ManyToManyField(blank=True, to='shop.ram', verbose_name='Озу'),
        ),
    ]
